Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

The returned dictionary should follow this format:

{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}
If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.

For example, calculate([0,1,2,3,4,5,6,7,8]) should return:

{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}

In [1]:
import numpy as np
def calculate(list):
    list = [5, 6, 7, 8, 4, 3, 3, 2, 1]
    if len(list) != 9:
        raise ValueError("List must contain nine numbers.")
    
    ls = np.array(list)
    print(ls)
    mean_cols = [ls[[0, 3, 6]].mean(), ls[[1, 4, 7]].mean(), ls[[2, 5, 8]].mean()]
    mean_rows = [ls[[0, 1, 2]].mean(), ls[[3, 4, 5]].mean(), ls[[6, 7, 8]].mean()]

    var_cols = [ls[[0, 3, 6]].var(), ls[[1, 4, 7]].var(), ls[[2, 5, 8]].var()]
    var_rows = [ls[[0, 1, 2]].var(), ls[[3, 4, 5]].var(), ls[[6, 7, 8]].var()]

    std_cols = [ls[[0, 3, 6]].std(), ls[[1, 4, 7]].std(), ls[[2, 5, 8]].std()]
    std_rows = [ls[[0, 1, 2]].std(), ls[[3, 4, 5]].std(), ls[[6, 7, 8]].std()]

    max_cols = [ls[[0, 3, 6]].max(), ls[[1, 4, 7]].max(), ls[[2, 5, 8]].max()]
    max_rows = [ls[[0, 1, 2]].max(), ls[[3, 4, 5]].max(), ls[[6, 7, 8]].max()]

    min_cols = [ls[[0, 3, 6]].min(), ls[[1, 4, 7]].min(), ls[[2, 5, 8]].min()]
    min_rows = [ls[[0, 1, 2]].min(), ls[[3, 4, 5]].min(), ls[[6, 7, 8]].min()]

    sum_cols = [ls[[0, 3, 6]].sum(), ls[[1, 4, 7]].sum(), ls[[2, 5, 8]].sum()]
    sum_rows = [ls[[0, 1, 2]].sum(), ls[[3, 4, 5]].sum(), ls[[6, 7, 8]].sum()]


    return {
    'mean': [mean_cols, mean_rows, ls.mean()],
    'variance': [var_cols, var_rows, ls.var()],
    'standard deviation': [std_cols, std_rows, ls.std()],
    'max': [max_cols, max_rows, ls.max()],
    'min': [min_cols, min_rows, ls.min()],
    'sum': [sum_cols, sum_rows, ls.sum()]
    }

calculate(list)
    


[5 6 7 8 4 3 3 2 1]


{'mean': [[5.333333333333333, 4.0, 3.6666666666666665],
  [6.0, 5.0, 2.0],
  4.333333333333333],
 'variance': [[4.222222222222222, 2.6666666666666665, 6.222222222222222],
  [0.6666666666666666, 4.666666666666667, 0.6666666666666666],
  4.888888888888888],
 'standard deviation': [[2.0548046676563256,
   1.632993161855452,
   2.494438257849294],
  [0.816496580927726, 2.160246899469287, 0.816496580927726],
  2.2110831935702664],
 'max': [[8, 6, 7], [7, 8, 3], 8],
 'min': [[3, 2, 1], [5, 3, 1], 1],
 'sum': [[16, 12, 11], [18, 15, 6], 39]}

In [2]:
def calculate(list):
    list = [2, 3, 4, 5, 6, 7, 8, 1, 2]
    if (len(list) != 9):
        raise ValueError("List must contain nine numbers.")    
        
    ls = np.array(list).reshape(3, 3)
    print(ls)
    
    mean = [ls.mean(axis=0).tolist(), ls.mean(axis=1).tolist(), ls.mean().tolist()]
    variance = [ls.var(axis=0).tolist(), ls.var(axis=1).tolist(), ls.var().tolist()]
    std_dev = [ls.std(axis=0).tolist(), ls.std(axis=1).tolist(), ls.std().tolist()]
    max_ = [ls.max(axis=0).tolist(), ls.max(axis=1).tolist(), ls.max().tolist()]
    min_ = [ls.min(axis=0).tolist(), ls.min(axis=1).tolist(), ls.min().tolist()]
    sum_ = [ls.sum(axis=0).tolist(), ls.sum(axis=1).tolist(), ls.sum().tolist()]

    return { 
    'mean': mean,
    
    'variance': variance,
    
    'standard deviation': std_dev,
    
    'max': max_,
    
    'min': min_,
    
    'sum': sum_

    }  
calculate(list)

[[2 3 4]
 [5 6 7]
 [8 1 2]]


{'mean': [[5.0, 3.3333333333333335, 4.333333333333333],
  [3.0, 6.0, 3.6666666666666665],
  4.222222222222222],
 'variance': [[6.0, 4.222222222222222, 4.222222222222222],
  [0.6666666666666666, 0.6666666666666666, 9.555555555555557],
  5.283950617283952],
 'standard deviation': [[2.449489742783178,
   2.0548046676563256,
   2.0548046676563256],
  [0.816496580927726, 0.816496580927726, 3.091206165165235],
  2.298684540619689],
 'max': [[8, 6, 7], [4, 7, 8], 8],
 'min': [[2, 1, 2], [2, 5, 1], 1],
 'sum': [[15, 10, 13], [9, 18, 11], 38]}

In [2]:
list = [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [4]:
import numpy as np
def calculate(list):
    list = [0, 1, 2, 3, 4, 5, 6, 7, 8]
    
    if len(list) != 9:
        raise ValueError('List must contain nine numbers.')
    
    ls = np.array(list)
    print(ls)
    mean_cols = [ls[[0, 3, 6]].mean(), ls[[1, 4, 7]].mean(), ls[[2, 5, 8]].mean()]
    mean_rows = [ls[[0, 1, 2]].mean(), ls[[3, 4, 5]].mean(), ls[[6, 7, 8]].mean()]

    var_cols = [ls[[0, 3, 6]].var(), ls[[1, 4, 7]].var(), ls[[2, 5, 8]].var()]
    var_rows = [ls[[0, 1, 2]].var(), ls[[3, 4, 5]].var(), ls[[6, 7, 8]].var()]

    std_cols = [ls[[0, 3, 6]].std(), ls[[1, 4, 7]].std(), ls[[2, 5, 8]].std()]
    std_rows = [ls[[0, 1, 2]].std(), ls[[3, 4, 5]].std(), ls[[6, 7, 8]].std()]

    max_cols = [ls[[0, 3, 6]].max(), ls[[1, 4, 7]].max(), ls[[2, 5, 8]].max()]
    max_rows = [ls[[0, 1, 2]].max(), ls[[3, 4, 5]].max(), ls[[6, 7, 8]].max()]

    min_cols = [ls[[0, 3, 6]].min(), ls[[1, 4, 7]].min(), ls[[2, 5, 8]].min()]
    min_rows = [ls[[0, 1, 2]].min(), ls[[3, 4, 5]].min(), ls[[6, 7, 8]].min()]

    sum_cols = [ls[[0, 3, 6]].sum(), ls[[1, 4, 7]].sum(), ls[[2, 5, 8]].sum()]
    sum_rows = [ls[[0, 1, 2]].sum(), ls[[3, 4, 5]].sum(), ls[[6, 7, 8]].sum()]


    return {
    'mean': [mean_cols, mean_rows, ls.mean()],
    'variance': [var_cols, var_rows, ls.var()],
    'standard deviation': [std_cols, std_rows, ls.std()],
    'max': [max_cols, max_rows, ls.max()],
    'min': [min_cols, min_rows, ls.min()],
    'sum': [sum_cols, sum_rows, ls.sum()]
    }

calculate(list)

    

[0 1 2 3 4 5 6 7 8]


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}